# Generated by Django 3.2.8 on 2022-03-02 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.category'),
        ),
    ]
