# Generated by Django 3.2.8 on 2021-11-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_student_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
