# Generated by Django 3.2.8 on 2022-03-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_teacher_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
