# Generated by Django 3.2.8 on 2021-11-22 15:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_teacher_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='week_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hours',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AM', ((0, '12:00 AM'), (1, '01:00 AM'), (2, '02:00 AM'), (3, '03:00 AM'), (4, '04:00 AM'), (5, '05:00 AM'), (6, '06:00 AM'), (7, '07:00 AM'), (8, '08:00 AM'), (9, '09:00 AM'), (10, '10:00 AM'), (10, '10:00 AM'), (11, '10:00 AM'))), ('PM', ((12, '10:00 PM'), (13, '01:00 PM'), (14, '02:00 PM'), (15, '03:00 PM'), (16, '04:00 PM'), (17, '05:00 PM'), (18, '06:00 PM'), (19, '07:00 PM'), (20, '08:00 PM'), (21, '09:00 PM'), (22, '10:00 PM'), (23, '11:00 PM')))], max_length=5),
        ),
    ]
