# Generated by Django 3.2.8 on 2022-03-10 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220310_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email_confirmed',
        ),
    ]
