# Generated by Django 3.2.8 on 2021-12-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish')], max_length=10)),
                ('number_of_lessons', models.PositiveSmallIntegerField()),
                ('package_price', models.DecimalField(decimal_places=2, default=0.0, help_text='in US dollars $', max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupportAndSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('supportUrl', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Support and sales',
            },
        ),
    ]
