# Generated by Django 3.2.8 on 2021-11-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='package_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='in US dollars $', max_digits=6),
        ),
    ]
