# Generated by Django 3.2.8 on 2021-11-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_pack_package_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAndSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('supportUrl', models.URLField()),
            ],
        ),
    ]
