# Generated by Django 3.2.8 on 2021-11-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_supportandsales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportandsales',
            options={'verbose_name_plural': 'Support and sales'},
        ),
    ]
