# Generated by Django 3.2.8 on 2021-11-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_supportandsales_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='pack',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='pack',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='lessons',
        ),
        migrations.AddField(
            model_name='pack',
            name='level',
            field=models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1'), ('c2', 'C2'), ('d1', 'D1'), ('d2', 'D2')], default='a1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pack',
            name='number_of_lessons',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
