# Generated by Django 3.2.8 on 2021-11-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20211122_2140'),
        ('lessons', '0005_auto_20211122_2140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
