# Generated by Django 3.2.8 on 2021-11-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_delete_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='level',
        ),
    ]
