# Generated by Django 3.2.8 on 2022-02-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
    ]
