# Generated by Django 3.2.8 on 2022-02-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=5, unique=True)),
                ('photo', models.ImageField(upload_to='photos')),
            ],
            options={
                'verbose_name': 'Photos',
                'verbose_name_plural': 'Photos',
                'ordering': ['week_day'],
            },
        ),
    ]
