# Generated by Django 3.2.8 on 2021-11-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authbg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authbg',
            name='day_of_the_week',
            field=models.CharField(choices=[('0', '1'), ('1', '2'), ('2', '3'), ('3', '4'), ('4', '5'), ('5', '6'), ('6', '7')], max_length=5),
        ),
    ]
