# Generated by Django 3.2.8 on 2021-11-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authbg', '0002_alter_authbg_day_of_the_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authbg',
            name='day_of_the_week',
            field=models.CharField(choices=[('0', '1'), ('1', '2'), ('2', '3'), ('3', '4'), ('4', '5'), ('5', '6'), ('6', '7')], max_length=5, unique=True),
        ),
    ]
