# Generated by Django 3.2.8 on 2021-11-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authbg', '0003_alter_authbg_day_of_the_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authbg',
            options={'ordering': ['day_of_the_week'], 'verbose_name': 'Auth Photos', 'verbose_name_plural': 'Auth Photos'},
        ),
        migrations.AlterField(
            model_name='authbg',
            name='day_of_the_week',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=5, unique=True),
        ),
    ]
