# Generated by Django 3.2.8 on 2021-11-21 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authbg', '0004_auto_20211121_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authbg',
            options={'ordering': ['week_day'], 'verbose_name': 'Auth Photos', 'verbose_name_plural': 'Auth Photos'},
        ),
        migrations.RenameField(
            model_name='authbg',
            old_name='day_of_the_week',
            new_name='week_day',
        ),
    ]
