# Generated by Django 3.2.8 on 2022-02-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lesson_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
