# Generated by Django 3.2.8 on 2022-03-14 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delete_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
