# Generated by Django 3.2.8 on 2022-03-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_task_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('finished', 'Finished')], default='active', max_length=10),
        ),
    ]
