# Generated by Django 3.2.8 on 2021-11-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20211102_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finish', 'Finish')], default='Active', max_length=10),
        ),
    ]
