# Generated by Django 3.2.8 on 2022-03-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=10),
        ),
    ]
