# Generated by Django 3.2.8 on 2021-11-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20211107_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finish', 'Finish')], default='active', max_length=10),
        ),
    ]
