# Generated by Django 3.2.8 on 2021-11-23 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
    ]
