# Generated by Django 3.2.8 on 2021-11-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_teacher_hours'),
        ('schedules', '0007_alter_task_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('teacher', 'date')},
        ),
        migrations.RemoveField(
            model_name='task',
            name='lesson',
        ),
    ]
