# Generated by Django 3.2.8 on 2021-11-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20211122_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lesson',
            field=models.CharField(default='1h lesson', max_length=20),
            preserve_default=False,
        ),
    ]
