# Generated by Django 3.2.8 on 2021-11-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_task_lesson_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lesson_link',
            field=models.URLField(blank=True),
        ),
    ]
