# Generated by Django 3.2.8 on 2021-11-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_alter_task_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pack',
        ),
    ]
