# Generated by Django 3.2.8 on 2021-11-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_remove_pack_level'),
        ('schedules', '0013_auto_20211123_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='packs',
        ),
        migrations.AddField(
            model_name='purchasedpackage',
            name='packs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.pack'),
            preserve_default=False,
        ),
    ]
