# Generated by Django 3.2.8 on 2021-11-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0014_auto_20211124_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedpackage',
            old_name='packs',
            new_name='pack',
        ),
    ]
